### ISSUE TITLE
Loss of room

### ISSUE THREAD

**Issue by jcaldwell02** [mets11rap/guildlink#1]
We discovered today that we no longer had our room anymore
Room name was bfvclannet
we had 3 discords setup with it and the last message was on june 6th

**Comment by exoRift** [comment]
Odd, the project is on hold until after finals where it will be rewritten, but even so, that shouldn't happen. I hope it doesn't happen again until I can pick back up on the project!

**Comment by exoRift** [comment]
GuildLink will be updated today.
