### ISSUE TITLE
Room is not running

### ISSUE THREAD

**Issue by Clamsy1111** [mets11rap/guildlink#5]
Hy, our room isn't running. And the Command |room ist with no reaction

**Comment by Clamsy1111** [comment]
and the command |list shows up:

Cannot read property 'room' of undefined

TypeError: Cannot read property 'room' of undefined
    at Command.action (/app/src/data/commands/list.js:16:64)

**Comment by exoRift** [comment]
Hi! Unfortunately, I haven't been able to work on GuildLink for a while. However, I recently have had more time to work on my projects and have been working hard on the engine GuildLink runs on. After I'm done working on the update for the engine, I'll be working on improving GuildLink again, so expect some... Instability when using GuildLink.

May I please ask for your room's name and the ID of the server it was created in?

**Comment by Clamsy1111** [comment]
Hy,

this screenshot is from 10/12/2019 and the bot has always worked until then. I can't tell you more, because the command |room doesn't work anymore and the command |list brings this error message.



Thanks
Martin

**Comment by exoRift** [comment]
The problem seems to be a mismatch with your server's ID so I need your server's ID or your server's name, please

**Comment by Clamsy1111** [comment]
how can I find the server ID?

GuildLink
#3508

Do you mean that?

**Comment by exoRift** [comment]
If you don't know how to get your server ID, you can just give me your server's name. That will suffice.

**Comment by Clamsy1111** [comment]
Our Server has the Name „Glaxay Stars“

Von meinem iPhone gesendet

**Comment by exoRift** [comment]
Is this the exact name of your server? It doesn't seem like the bot is in any server named "Galaxy Stars" or anything similar. Is it in German perhaps?

**Comment by Clamsy1111** [comment]
I do not know which server name or ID to use?

Just come to our server, then we can talk better.

https://discord.gg/aUPDcfP

**Comment by Clamsy1111** [comment]
I Found the Server ID:

541316995757637652

**Comment by exoRift** [comment]
I'm looking in the database and your server is not anywhere in there. Are you sure you joined the room? (Also, are you using the official bot or is someone else hosting it)

**Comment by Clamsy1111** [comment]
Hello, I have created the room and I am the owner. I have shared the room with another server, and this one has joined as well.

It has worked perfectly since 10/12/2019. Nothing has been changed. The bot stopped working on 05/14/2020 during the day.

We have always used the original of the bot, so yours.

Do you have a backup where you can see that our server is listed there? So a backup before the 05/14/2020?

**Comment by exoRift** [comment]
Unfortunately, my bot is hosted freely and the database does not have automatic backups. Did you or an admin on your server accidentally delete your room? There is no evidence of it or your friend's server in the database. (When I begin working on the next update, I'll be sure to include logs for creating and deleting rooms. I'm sorry that the bot is so unstable right now.)

**Comment by exoRift** [comment]
Actually, I might be able to check. Around what date did the bot stop working?

**Comment by Clamsy1111** [comment]
It stop during the 14 May 2020

Von meinem iPhone gesendet

**Comment by exoRift** [comment]
Sorry, but I was unable to find any records of deletion. I apologize for the problem. Maybe somebody deleted the room accidentally, I don't know. All I can tell you is that your room in not in the database.

**Comment by exoRift** [comment]
I can tell you though, I'm very close to being able to work on an update for GuildLink, so stay tuned for a better experience with the bot!

**Comment by Clamsy1111** [comment]
How can I recreate the room? The |room command does not respond.

**Comment by exoRift** [comment]
It doesn't respond or it returns an error?

**Comment by exoRift** [comment]
Ah, it seems the bot can't even start due to a bad practice that has caught up. I'm very sorry, but you won't be able to use the bot until I release an update :/ I'm really sorry for all the trouble I've caused.

**Comment by exoRift** [comment]
Good news! The update is in progress at a steady pace with a lot done so far! You can check the progress [here](https://github.com/exoRift/guildlink/projects/1)
